# Generated by Django 4.0.5 on 2022-06-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_genre_alter_movies_options_directors_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
