# Generated by Django 4.0.5 on 2022-06-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_directors_born_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='cinema.movies'),
        ),
    ]
